CREATE TABLE T_CHANNEL_INFO(
ID INTEGER PRIMARY KEY autoincrement,
AREA_ID 		VARCHAR(10),
AREA_NAME 		VARCHAR(128),
CHNL_NO 		VARCHAR(10),
CHANNEL_NAME	VARCHAR(128),
I_E_TYPE 	 	VARCHAR(2),
CONFIG_TIME	 	DATETIME
);



