CREATE TABLE T_GATHERINFO_PASS(
ID INTEGER PRIMARY KEY autoincrement,
AREA_ID 	VARCHAR(10),
CHNL_NO 	VARCHAR(10),
I_E_TYPE 	VARCHAR(2),
SEQ_NO 		VARCHAR(20),
CHECK_RESULT 		VARCHAR(32),
VE_NAME 			VARCHAR(32),
GPS_ID 				VARCHAR(32),
ORIGIN_CUSTOMS 		VARCHAR(32),
DEST_CUSTOMS 		VARCHAR(32),
CONTA_NUM 			VARCHAR(2),
ESEAL_ID 			VARCHAR(32),
SEAL_KEY 			VARCHAR(32),
FORM_ID 			VARCHAR(32),
OP_HINT 			VARCHAR(255),
PASS_TIME			DATETIME
);



